=== trucka312/XML_teach_doc/HangHoa/SieuThi/SieuThi.xsd
<xsd:schema version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" elementFromDefault="qualified">
    <xsd:element name="SieuThi">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="TenSieuThi" type="xsd:string" />
                <xsd:element name="DiaChi" type="xsd:string" />
                <xsd:element name="SoDienThoai" type="xsd:string" />
                    <xsd:simpleType > 
                        <xsd:restriction base="xsd:interger">
                            <xsd:pattern value="[0,9]{10,11}" />
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>

                <xsd:element name="HangHoa" maxOccurs="100" minOccurs="3">
                    <xsd:complexType >
                        <xsd:sequence>
                            <xsd:element name="TenHang" type="xsd:string" />
                            <xsd:element name="LoaiHang" >
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string" />
                                        <xsd:enumeration value=" bình thường " />
                                        <xsd:enumeration value=" Khuyến Mại " />
                                    </xsd:restriction> 
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element name="SoLuong" >
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:interger" />
                                        <xsd:maxExclusive value="201" />
                                        <xsd:minExclusive value="0" />
                                    </xsd:restriction> 
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="DonGia" type="xsd:double" />
                        </xsd:sequence>
                        <xsd:attribute name="MaHang" >
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:ID" />
                                    <xsd:pattern value="[a-zA]{2}[0-9]{2}" />
                                </xsd:restriction> 
                            </xsd:simpleType>
                        </xsd:attribute>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== trucka312/XML_teach_doc/HangHoa/SieuThi/SieuThi.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet href="SieuThi.xsl" type="text/xsl" ?>
<SieuThi xmlns="" xmlns:xsd="http:www.w3.org/2001/XMLSchema" xsd:schemaLocation="SieuThi.xsd" >
    <TenSieuThis>Winmart</TenSieuThi>
    <DiaChi>Hai Ba Trung</DiaChi>
    <SoDienThoai>0000000000</SoDienThoai>
    <HangHoa MaHang="H01">
        <TenHang>Mì Tôm </TenHang>
        <LoaiHang>Khuyến Mại</LoaiHang>
        <SoLuong>20</SoLuong>
        <DonGia>200000</DonGia>
    </HangHoa>

    <HangHoa MaHang="H02">
        <TenHang>Trứng </TenHang>
        <LoaiHang>bình thường</LoaiHang>
        <SoLuong>300</SoLuong>
        <DonGia>4500</DonGia>
    </HangHoa>

    <HangHoa MaHang="H03">
        <TenHang>Sữa Onoh Thọ</TenHang>
        <LoaiHang>Khuyến Mại</LoaiHang>
        <SoLuong>13</SoLuong>
        <DonGia>21000</DonGia>
    </HangHoa>
</SieuThi>
